### ISSUE TITLE
training with a new dataset

### ISSUE THREAD

**Issue by peterthorpe5** [hsgweon/pipits#1]
Dear Pipits,

Thank you for the tool, I wish to try this with my data, which is not fungal. Therefore I would have to retrain rdp.

when I type:
$ pipits_retrain_rdp -h
usage: Retrains RDP Classifier [-h] -j <JAR> -f <FASTA> -t <TAXONOMY> -o DIR

optional arguments:
  -h, --help     show this help message and exit
  -j <JAR>       [REQUIRED] RDP Classifier .jar file
  -f <FASTA>     [REQUIRED] UNITE training data - FASTA sequences downloaded
                 from http://sourceforge.net/projects/rdp-
                 classifier/files/RDP_Classifier_TrainingData
  -t <TAXONOMY>  [REQUIRED] UNITE training data - taxonomy file downloaded
                 from http://sourceforge.net/projects/rdp-
                 classifier/files/RDP_Classifier_TrainingData
  -o DIR         Output directory where files and settings for retrained
                 parameters are stored.

All the above help-info is related to the trained project. Would you be able to add a help page on github regarding retraining and how to prepare the .xml file which has the taxonomy tree? Would this work if I gave it a fasta file of sequences and an xml formatted tree ... or is it more complicated than that? 

Also, would that mean I would have to alter the enviroment variable: export PIPITS_UNITE_RETRAINED_DIR=$HOME/pipits/refdb/UNITE_retrained
to my new trained data? Or can you pass this as an argument when it is required?

regards,

Peter Thorpe

**Comment by hsgweon** [comment]
Apologies, but you will have to refer to RDP Classifier's webpage (https://sourceforge.net/projects/rdp-classifier/) and their documents for retraining a custom dataset as I don't intend to make a tutorial/help page/manual on the dependencies.

**Comment by peterthorpe5** [comment]
Thank you for your response - being pointe in the right direction was all that was needed :) 

cheers, Pete
