### ISSUE TITLE
More counts than read pairs

### ISSUE THREAD

**Issue by kunstner** [hsgweon/pipits#11]
Hi @hsgweon,

I recently started to use PIPITS to analyse ITS1 data and I came across an issue. Maybe it isn't really an issue and I just lack some understanding of the algorithm behind PIPITS.

I have a couple of samples where the biom file (and the otu table as well) shows actually more counts than raw read pairs. 
For instance, I have a sample with 31,371 raw read pairs. If I just sum over all mapped contigs in the biom file (R command: apply(phyloseq::otu_table(x), 2, sum )) I get 124,475 features/contigs mapping for this particular sample. 

Do you have any explanation for this behaviour?

I'm running PIPITS2 following the installation instructions from the github page. I tested PIPITS on a Linux platform and on macOS 10.13.5 with the same results.

Best,
 Axel

**Comment by hsgweon** [comment]
Hi Axel,

No that should never happen. Can you let me know what values you were seeing in the “summary.log” from each of the processes (pispino_seqprep, pipits_funits and pipits_process)?

Best,
Soon

**Comment by kunstner** [comment]
Hi @hsgweon,

here are the summary logs from the different processes.

pispino_seqprep:

- Number of reads: 560792
- Number of joined reads: 463913
- Number of quality filtered reads: 458411
- Number of prepped sequences: 458411

pipits_funits:

- Number of input sequences: 458411
- Number of dereplicated sequences: 123648
- Number of ITS sequences (dereplicated): 122633
- Number of length-filtered sequences (dereplicated): 122549
- Number of sequences with ITS subregion: 457186

pipits_process:

- No.of reads used to generate OTU table: 454255
- Number of OTUs:                         943
- Number of phylotypes:                   207
- Number of samples:                      21

Just let me know if you need more information.

Best,
 Axel

**Comment by hsgweon** [comment]
Hmm... sorry I don't think I understand the problem. I thought you were talking about the number of OTUs and everything looks quite normal. Is the problem related to your biom file? Can you elaborate your problem a little bit more?

**Comment by hsgweon** [comment]
Ah... I think I understand what you mean. So, for a sample with only a few reads, why are we seeing more features? That's possibly because it's also counting zero-entries? Can you have a look at the OTU table in Excel and see if that's the case?

**Comment by kunstner** [comment]
I just uploaded the OTU table (generated from the biom file):

https://www.dropbox.com/s/t12xlffnvp6auq7/OTU_table_sums_incl.txt.zip?dl=0

The last row shows the total counts per sample. I would expect that the total count per sample cannot be larger than the number of reads/contigs surviving the preprocessing steps, right? For instance sample T10 (first column) has a total count of  124,475 but the number of raw reads is only 31,371. I wonder how the total counts can be larger than the number of reads/contigs surviving the preprocessing.

**Comment by hsgweon** [comment]
For your "prepped.fasta" after pispino_seqprep, can you run:

grep "^>T10_" prepped.fasta | wc

and let me know how many entries you see?

**Comment by kunstner** [comment]
The number fits what I expected:

```
$cat pipits/out_seqprep/prepped.fasta | grep -c "^>T10_"
26841
```

**Comment by hsgweon** [comment]
I am assuming the same with "out_funits/ITS.fasta"?

**Comment by kunstner** [comment]
Unfortunately not. Here, the number matches roughly the number of total counts from the OTU table:

```
cat /Users/axel/Projects/00_progress/58_Mycobiome_Swiss/pipits/out_funits/ITS.fasta |  grep -c "^>T10_"
125163
```

**Comment by hsgweon** [comment]
Ok, it looks like something is not right with VSEARCH's re-inflating feature. Can you let me know which VSEARCH version you are using? I will look into this as a matter or urgency and will get back to you.

**Comment by kunstner** [comment]
On both systems it is version 2.7.0
```
cat out_funits/versions.log | grep vsearch
vsearch                   2.7.0                         1    bioconda
```

Thanks for having a look on it.

**Comment by hsgweon** [comment]
Hi Axel, thanks to you a major bug affecting PIPITS2 has been found. I have essentially rolled back "dereplication" and "reinflation" part back to PIPITS1 instead of using VSEARCH. I have tested the code on my data and it looks to be behaving as expected. 

Can you update PIPITS by "conda update pipits" and see if it works as expected for you? I've also updated the main page to let users know of the fix.

**Comment by kunstner** [comment]
Hi @hsgweon,
the bug seems to be fixed. 
I'm getting 26,345 contigs mapped for T10, which seems to be more than reasonable. Additionally, I had the feeling that it is running much faster now compared with the vsearch version.
Thanks for fixing it so quickly!
Best,
 Axel

**Comment by hsgweon** [comment]
Excellent! If you have any other issue or suggestions, do let me know.
