### ISSUE TITLE
major problem with pispino_seqprep and VSEARCH

### ISSUE THREAD

**Issue by DelmoPy** [hsgweon/pipits#13]
First of all I would like to thank you for the pipeline.

Lately when running pispino_seqprep on default, from about 1 000 000 sequences only 5 came out of the process and when trying to do the next step no sequences survived. I've changed the default joiner method with PEAR (it comes with microbiome helper) but I'm not sure if I'm getting good results. The final taxa seems to not be correct and there is a huge variance between samples (maybe this last part is my fault in some way).

Hope this comment helps

**Comment by hsgweon** [comment]
So, a few questions:

1. What is the length of the overlapping region between the forward and reverse reads? You can infer this from the primers are you using. 

2. It could be that the quality of the sequences aren't good enough to be joined. 

I'm surprised that only 5 came out! For whatever reason, if your sequences cannot be joined, you may have to just use the forward reads. So you can supply the secret parameter when running pispino_seqprep

--forwardreadsonly 

So, for example:

pispino_seqprep -i rawdata -o pispino_seqprep_output -l readpairslist.txt --forwardreadsonly

Do let me know how you get on!

Soon
