### ISSUE TITLE
Retrain UNITE fungal data.

### ISSUE THREAD

**Issue by davidvilanova** [hsgweon/pipits#14]
Hi,
I´m cleaning up UNITE files to only include a subset and would like to retrain the files on RDP. I´ve seen that you provide already retrained files but would like to retrain on my subset.

Is there any script available to do that ?

**Comment by hsgweon** [comment]
Hi, it's probably best if you address this problem to: https://github.com/rdpstaff/classifier for any RDP related issues including training. Thanks!
