### ISSUE TITLE
Issue rereplicating

### ISSUE THREAD

**Issue by wzacs1** [hsgweon/pipits#15]
Thanks for a great pipeline. Very nice.  
I hope I'm not missing something obvious about my environment here, but this ModuleNotFoundError seems odd.  Any help is greatly appreciated.  2.2 is just installed and everything running fine until pipits_funits.  pipits can't find pipits module?  I'm running on a cluster with Anaconda3. Here's the last few lines from the log (my paths changed to $HOME):

Traceback (most recent call last):
  File "$HOME/.conda/envs/pipits_env/bin/pipits_rereplicate", line 31, in <module>
    from pipits import pipits_SeqIO as SeqIO
ModuleNotFoundError: No module named 'pipits'
ESC[91m2018-08-02 17:08:34ESC[0m Error: None zero returncode: python $HOME/.conda/envs/pipits_env/bin/pipits_rereplicate -i ITS2ExtractOut/intermediate/derep.ITS2.sizefiltered.fasta -o ITS2ExtractOut/ITS.fasta --uc ITS2ExtractOut/intermediate/derep.uc

Thanks!

**Comment by hsgweon** [comment]
Hi. It means python path is not set properly. And it looks like your env location is not in the usual place. Where did you install Anaconda3? Personally I would suggest reinstalling Anaconda3/Miniconda3 locally, and then install PIPITS as suggested.

**Comment by wzacs1** [comment]
Thanks.  I'm on a cluster environment where Anaconda and miniconda are in modules I have to load, and in directories I cannot access.  I thought the path was off given other replies to other issues, and the python was indeed referring to the module version, which I don't have access, to but even when I explicitly set path to the python at $HOME/.conda/envs/pipits_env/bin/python it still threw this error.  I tried loading our installed miniconda module instead and path is already set to python in pipits_env directory and works like a charm.  Not sure I understand what is happening in the different Anaconda3 and miniconda3 modules we have, but this did the trick. Thanks for your hints.
