### ISSUE TITLE
problem with pipits_funits

### ISSUE THREAD

**Issue by JuuKa** [hsgweon/pipits#16]
Hi,

I have a problem with running pipits_funits. Other data sets have been successful. Two attached files are a "output.log" and a "versions.log". 
Do you have solution for this? 

Thank you for your help.
[output.log](https://github.com/hsgweon/pipits/files/2334534/output.log)
[versions.log](https://github.com/hsgweon/pipits/files/2334537/versions.log)

**Comment by hsgweon** [comment]
@JuuKa I don't quite understand your question. Other data sets have run successfully? do you mean you've managed to run PIPITS from pipits_prep to pipits_process with other datasets?

Can you let me know if you are able to run "hmmscan" in your command? So, type "hmmscan -h" in your terminal and see if you get an error or a help page?

**Comment by JuuKa** [comment]
Thank you very much for your quick response.

I have managed to run PIPITS from pipits_prep to pipits_process with other dataset. A log-file "output2.log" without problem is attached as an example.

The "hmmscan -h" is working and I can get a help page in my terminal.

[output2.log](https://github.com/hsgweon/pipits/files/2338502/output2.log)

**Comment by hsgweon** [comment]
Can you possibly run that failed part of PIPITS_FUNITS in command line?

So, assuming you are in the correct directory:

`ITSx -i out_funits2B/intermediate/derep.fasta -o out_funits2B/intermediate/derep --preserve T -t F --cpu 1 --save_regions ITS2`

**Comment by JuuKa** [comment]
Thank you very much for your response.

I typed "`nohup ITSx -i out_funits2B/intermediate/derep.fasta -o out_funits2B/intermediate/derep --preserve T -t F --cpu 1 --save_regions ITS2`" in my terminal and I could see "`11:54 hmmsearch --cpu 1 --max -T . . . /ITSx_db/HMMs/F.hmm ITSx_temp_directory__out_funits2B-intermediate-derep/main.fasta`" in another terminal.

And, the following is a log in "drep.summary.txt".
```
ITSx run started at Fri Aug 31 17:07:35 2018.
---------------------------------------------------------
Number of sequences in input file:       	2029790
```

I will let you know when I get this result.

**Comment by hsgweon** [comment]
Hmm. I don't know whether that will finish without error... but I think some others were experiencing a similar problem with a large dataset on their machine anyway. 

I know this is not ideal, but can you try to divide your dataset into few files, and then run PIPITS_FUNITS? You can then merge the output FASTA as an input for PIPITS_PROCESS... if this makes sense...

**Comment by JuuKa** [comment]
Thank you very much for your answer and advice.

I will try to run PIPITS_FUNITS with a divided dataset. 

Thank you so much for your kind responses.
