### ISSUE TITLE
pipits_funits

### ISSUE THREAD

**Issue by igo111** [hsgweon/pipits#17]
Hi

I have a problem with running pipits_funits with test dataset 

(pipits_env) bio@biolinux-All-Series:~/pipits$ pipits_funits -i out_seqprep/prepped.fasta -o out_funits -x ITS2 -v
pipits_funits 2.2, the PIPITS Project
https://github.com/hsgweon/pipits
---------------------------------

2018-09-03 18:59:17 pipits_funits started
2018-09-03 18:59:17 Checking input FASTA for illegal characters
2018-09-03 18:59:17 ... done
2018-09-03 18:59:17 Counting input sequences
2018-09-03 18:59:17 ... number of input sequences: 53
2018-09-03 18:59:17 Dereplicating sequences for efficiency
vsearch v2.8.2_linux_x86_64, 15.6GB RAM, 8 cores
https://github.com/torognes/vsearch

Dereplicating file out_seqprep/prepped.fasta 100%
13859 nt in 53 seqs, min 239, max 370, avg 261
Sorting 100%
20 unique sequences, avg cluster 2.6, median 2, max 11
Writing output file 100%
Writing uc file, first partSegmentation fault (core dumped)
2018-09-03 18:59:17 Error: None zero returncode: vsearch --derep_fulllength out_seqprep/prepped.fasta --output out_funits/intermediate/derep.fasta --uc out_funits/intermediate/derep.uc --fasta_width 0 —sizeout

Do you have solution for this?
Thank you for your help.

**Comment by hsgweon** [comment]
Hi @igo111 
It appears that your PC doesn't have enough RAM. Can you let me know what the spec of your machine is?

**Comment by igo111** [comment]
Thank you very much for your quick response.
lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 60
Model name:            Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
Stepping:              3
CPU MHz:               3400.132
CPU max MHz:           3900.0000
CPU min MHz:           800.0000
BogoMIPS:              6785.03
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              8192K
NUMA node0 CPU(s):     0-7

cat /proc/meminfo
MemTotal:       16336304 kB
MemFree:         2974340 kB
MemAvailable:   13456416 kB
Buffers:          563284 kB
Cached:          9638372 kB
SwapCached:          344 kB
Active:          8431188 kB
Inactive:        3979944 kB
Active(anon):    1935844 kB
Inactive(anon):   391876 kB
Active(file):    6495344 kB
Inactive(file):  3588068 kB
Unevictable:          48 kB
Mlocked:              48 kB
SwapTotal:      16383996 kB
SwapFree:       16382652 kB
Dirty:               120 kB
Writeback:             0 kB
AnonPages:       2209184 kB
Mapped:           570224 kB
Shmem:            118252 kB
Slab:             788812 kB
SReclaimable:     734796 kB
SUnreclaim:        54016 kB
KernelStack:       13616 kB
PageTables:        48180 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    24552148 kB
Committed_AS:    8974904 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      258688 kB
DirectMap2M:     9082880 kB
DirectMap1G:     8388608 kB

**Comment by hsgweon** [comment]
Can you try running:
```
cd ~/pipits

pipits_funits -i out_seqprep/prepped.fasta -o out_funits -x ITS2 -v -r
```
This should reproduce the error. "-r" will retain intermediate files.

Then run the following?
```
vsearch --derep_fulllength out_seqprep/prepped.fasta --output out_funits/intermediate/derep.fasta --uc out_funits/intermediate/derep.uc --fasta_width 0 —sizeout
```

**Comment by igo111** [comment]
(pipits_env) bio@biolinux-All-Series:~/pipits$ pipits_funits -i out_seqprep/prepped.fasta -o out_funits -x ITS2 -v -r
pipits_funits 2.2, the PIPITS Project
https://github.com/hsgweon/pipits
---------------------------------

2018-09-03 19:41:35 pipits_funits started
2018-09-03 19:41:35 Checking input FASTA for illegal characters
2018-09-03 19:41:35 ... done
2018-09-03 19:41:35 Counting input sequences
2018-09-03 19:41:35 ... number of input sequences: 53
2018-09-03 19:41:35 Dereplicating sequences for efficiency
vsearch v2.8.2_linux_x86_64, 15.6GB RAM, 8 cores
https://github.com/torognes/vsearch

Dereplicating file out_seqprep/prepped.fasta 100%
13859 nt in 53 seqs, min 239, max 370, avg 261
Sorting 100%
20 unique sequences, avg cluster 2.6, median 2, max 11
Writing output file 100%
Writing uc file, first partSegmentation fault (core dumped)
2018-09-03 19:41:35 Error: None zero returncode: vsearch --derep_fulllength out_seqprep/prepped.fasta --output out_funits/intermediate/derep.fasta --uc out_funits/intermediate/derep.uc --fasta_width 0 --sizeout

(pipits_env) bio@biolinux-All-Series:~/pipits$ vsearch --derep_fulllength out_seqprep/prepped.fasta --output out_funits/intermediate/derep.fasta --uc out_funits/intermediate/derep.uc --fasta_width 0 —sizeout


Unrecognized string on command line (—sizeout)
(pipits_env) bio@biolinux-All-Series:~/pipits$ vsearch --derep_fulllength out_seqprep/prepped.fasta --output out_funits/intermediate/derep.fasta --uc out_funits/intermediate/derep.uc --fasta_width 0 --sizeout


Unrecognized string on command line (�)

**Comment by igo111** [comment]
Sorry, this is result for the second command

(pipits_env) bio@biolinux-All-Series:~/pipits$ vsearch --derep_fulllength out_seqprep/prepped.fasta --output out_funits/intermediate/derep.fasta --uc out_funits/intermediate/derep.uc --fasta_width 0 --sizeout
vsearch v2.8.2_linux_x86_64, 15.6GB RAM, 8 cores
https://github.com/torognes/vsearch

Dereplicating file out_seqprep/prepped.fasta 100%  
13859 nt in 53 seqs, min 239, max 370, avg 261
Sorting 100%
20 unique sequences, avg cluster 2.6, median 2, max 11
Writing output file 100% 
Writing uc file, first part 0%Segmentation fault (core dumped)

**Comment by hsgweon** [comment]
Ok this is annoying but the recently updated version of VSEARCH (2.8.2) has a bug when building uc file. Can you please downgrade VSEARCH to 2.8.0 until they've sorted this issue?

So assuming you are in the PIPITS env `source activate pipits_env`, please downgrade VSEARCH by:

```
conda install vsearch=2.8.0
```

And then try PIPITS again with the testdata and let me know if everything works?

**Comment by igo111** [comment]
After I downgrade vsearch everything works.
Thank you so much!

**Comment by hsgweon** [comment]
I think others might find this useful, so thank YOU. I will keep this thread open until VSEARCH guys have fixed the bug.

**Comment by AMFBio** [comment]
Hi @hsgweon 

I'm getting a similar error as above: [[0m Error: None zero returncode: vsearch --uchime_ref out_process/intermediate/input_nr_otus.fasta --db $PIPITS_UNITE_REFERENCE_DATA_CHIMERA --nonchimeras out_process/intermediate/inp$

I downgraded to vsearch 2.8.0 however I'm still getting this exact error.

Are you able to shed any light on this?

Cheers

**Comment by AMFBio** [comment]
Hi @hsgweon - just checking if you can comment on this?

**Comment by DrCBG** [comment]
Just FYI, this bug still exists in the most recent version of VSEARCH.

**Comment by hsgweon** [comment]
I have just tested PIPITS 2.3 on a freshly installed Ubuntu 18.04 (LTS) and macOS (Mojave), and all ran without any issues. I will close this for now.
