### ISSUE TITLE
Unable to run pipits 

### ISSUE THREAD

**Issue by slvrshot** [hsgweon/pipits#2]
I am running the command

` pipits_funits -i combined_seqs.fasta -o pipits_funits -x ITS2`

Here are my headers: 

```
>ITS.Rev.B.1.S138_0 M02849:171:000000000-ANHND:1:1101:20355:1874_1:N:0:138
GGTACTAGAGGAAGTAAAAGTCGTAACAAGGTTTCCGTAGGTGAACCTTCGGAAGGATCATTAAATAATTTTTAATTTTTATTCTTCGCGTTATATTCTTAATATATTTTACTGTGAACTGTATTATTTCATTACGCTTGATTAATCCTTCTGCTTTACCATAATGGACAGTTCATCGAAGATGTTAACCGAGTCGTGGTCAAGCTTATCCTTGGTGTCCTTAATTATTATTCTCCAAAAGAATTCATTTTAAAAATATTTTAATATGGGCTTAAAAAACTCATTAAAACAACTTTTAAC

>ITS.Rev.B.1.S138_1 M02849:171:000000000-ANHND:1:1101:22962:1969_1:N:0:138
GGTACTAGAGGAAGTAAAAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCGTAAGGATCATTACCGAGTGCGGGCCCTCTGGGTCCAACCTCCCATCCGTGTCTATCTGTACCCTGTTGCTTCGGCGTTTCCTCGGCCCGCCGCAGACTAACATTTTAACACTGTCTGAAGTTTGCAGTCTGAGTTTTTAGTTAAACAATAATTAAAACTTTCAACAACTTATCTCTTGGTTCCGTCATCGATGAAGAACGCAGCGAAATGCGATAATTAATTTGAATTTCAGAATTCAGTGAATCTTCG
```

**Comment by slvrshot** [comment]
Also these sequences were generated from ITS1-ITS4 primers which amplify the entire ITS region; however because it was done a MiSeq the majority of reads will not merge due to read length. Shouldn't I still be able to use these sequences and specify which region I want to extract rather that is ITS1 or ITS2? For example Read1 should in theory be mostly ITS1. Thanks!

**Comment by hsgweon** [comment]
That's correct, Read 1 should mostly be ITS1 while Read 2 = ITS2.

And you probably won't get many reads back from PIPITS_PREP as you used ITS1-ITS4. However, it looks like you've managed to produce a FASTA file with the required headers for PIPITS_FUNITS and PIPITS_PROCESS, so you should be able to select one of the two regions and get the desired result.

**Comment by slvrshot** [comment]
Thanks for replying so fast @hsgweon ! My lab is really interested in integrating this pipeline into our research. I do have a few additional questions:

First, when I run my sequencing data that had already been pre-processed (trimmed, filtered based on size, and merged) from Geneious into the pipeline I get this message:
```


[2017-03-23 20:40:42 INFO: PIPITS_FUNITS started
2017-03-23 20:40:42 INFO: Checking input FASTA for illegal characters
2017-03-23 20:40:42 INFO: Counting input sequences
2017-03-23 20:40:42 INFO: 	Number of input sequences: 2900
2017-03-23 20:40:42 INFO: Dereplicating sequences for efficiency
2017-03-23 20:40:42 INFO: Extracting ITS1 from sequences [ITSx]
2017-03-23 20:40:43 INFO: Removing sequences below < 100bp
2017-03-23 20:40:43 INFO: Re-inflating sequences
2017-03-23 20:40:43 INFO: Counting sequences after re-inflation
2017-03-23 20:40:43 INFO: 	Number of sequences with ITS subregion: 0
2017-03-23 20:40:43 INFO: Have you chosen the right subregion? Exiting as no sequences to process.
MR_Fungi-Mac-Pro:pipits twpierson$ 



```
Secondly, why is it necessary to extract the ITS regions if that is what we were amplifying - shouldn't all the sequences be ITS? I've read over the paper a few times and I'm still not sure why this matters. My lab has been using QIIME with the lastest UNITE database, and it seems to work okay (you have to set the assignment method to blast otherwise half of the reads go unassigned) but it still may not be ideal....hence why I'm trying to use your program. 

I've also attached some sequences files for ITS2 that I also tested and didn't seem to work. The sequences above are my Read1s from our ITS1-4 amplicons.

Thanks,
[ITS2.6.fasta.zip](https://github.com/hsgweon/pipits/files/866561/ITS2.6.fasta.zip)

**Comment by hsgweon** [comment]
Hi, I'm not sure why you aren't getting any sequences back from PIPTIS_FUNITS. This generally happens if you haven't re-HMMPressed your profiles (See instruction: 1.5 Re-HMMPressing). I just ran your sequences on our system and got:

pipits_funits -i ITS2.6.fasta -o pipits_process -x ITS1                                                                                                                                                                                             

2017-03-27 20:36:41 INFO: PIPITS_FUNITS started
2017-03-27 20:36:41 INFO: Checking input FASTA for illegal characters
2017-03-27 20:36:41 INFO: Counting input sequences
2017-03-27 20:36:41 INFO: 	Number of input sequences: 2900
2017-03-27 20:36:41 INFO: Dereplicating sequences for efficiency
2017-03-27 20:36:41 INFO: Extracting ITS1 from sequences [ITSx]
2017-03-27 20:38:17 INFO: Removing sequences below < 100bp
2017-03-27 20:38:17 INFO: Re-inflating sequences
2017-03-27 20:38:17 INFO: Counting sequences after re-inflation
2017-03-27 20:38:17 INFO: 	Number of sequences with ITS subregion: 2895
2017-03-27 20:38:17 INFO: Cleaning temporary directory
2017-03-27 20:38:17 INFO: PIPITS_FUNITS ended successfully. "ITS.fasta" created in "pipits_process"
2017-03-27 20:38:17 INFO: Next Step: PIPITS_PROCESS [ Example: pipits_process -i pipits_process/ITS.fasta -o pipits_process ]


Regarding the second question, the features of FUNITS is to (1) Extract fungal sequences (2) Remove conserved regions near the priming sites. (3) Re-orientate sequences if necessary.

Of course you can run your data without PIPITS_FUNITS and go straight to PIPITS_PROCESS if you know your sequences well.

**Comment by slvrshot** [comment]
@hsgweon Awesome, I was able to work through those issues. Your pipeline works great. I look forward to citing in my paper.

One recommendation in a future update is to integrate the UNITE taxonomy within the OTU table.

**Comment by hsgweon** [comment]
Thanks for that. 
The generated OTU table has a column with the UNITE taxonomy (LCA) 
The full Unite taxonomy (I am guessing that's what you want) can be found in a file called "assigned_taxonomy.txt" which is produced by PIPITS_PROCESS.

If you have any questions, do let me know and I would welcome any suggestions.

**Comment by slvrshot** [comment]
@hsgweon I was curious what is the performance benchmark for your implementation of ITSx and if the extraction command (PIPITS_FUNITS) can allow multi-threading or parallelization? The regular ITSx is currently not built for multithreading. 

We have an 2 x 2.8 GHz Quad-Core Intel Xeon, 24 GB of RAM....it took 5 mins to run PIPITS_FUNITS using 12 threads on 5503 sequences. Is there a way to speed this up? Eventually I may be working with over 3 million sequences which could take close to 2 days to run. 

Thanks!!!

**Comment by ghost** [comment]
Hi sorry for the delay. ITSx does implement multithreading for multiple phyla group libraries. For example, if you want to filter for fungi and plants, then ITSx can divide the job into two CPUs. In our case though, we only search our sequences against fungal library, so unfortunately ITSx cannot use multithreading. This is something ITSx developers will have to work on as it's not going to be hugely difficult to get multithreading implemented with a single library. Of course I would love to address the issue myself and make my own "classifier", and I plan to do so when I get some further funding (easier said than done!)

**Comment by AMFBio** [comment]
Hi @hsgweon ,

I'm having the same problem as above; I'm getting the error below with a data set I'm trying to analyse. I can analyse other, smaller, data sets no problem - but this one won't work? I can't attached the zipped file as it's too big - let me know if I can send to you another way.

(qiime2-2017.12) qiime2@qiime2core2017-12:/media/sf_Sequencing$ time pipits_funits -i pipits_prep/prepped.fasta -o pipits_funits -x ITS2
2018-10-30 04:06:31 INFO: PIPITS_FUNITS started
2018-10-30 04:06:31 INFO: Checking input FASTA for illegal characters
2018-10-30 04:06:38 INFO: Counting input sequences
2018-10-30 04:06:41 INFO: 	Number of input sequences: 1825704
2018-10-30 04:06:41 INFO: Dereplicating sequences for efficiency
2018-10-30 04:13:12 INFO: Extracting ITS2 from sequences [ITSx]
2018-10-30 04:16:50 INFO: Removing sequences below < 100bp
2018-10-30 04:16:51 INFO: Re-inflating sequences
2018-10-30 04:16:54 INFO: Counting sequences after re-inflation
2018-10-30 04:16:54 INFO: 	Number of sequences with ITS subregion: 0
2018-10-30 04:16:54 INFO: Have you chosen the right subregion? Exiting as no sequences to process.

I've blasted some of my files in Geneious so I know that there are ITS sequences there. 

Do you have any advice? I've already re-HMMPressed my profiles, however I'm getting the following error when I do this: Error: File format problem in trying to open HMM file N.hmm. File exists, but appears to be empty? 

So I'm not sure if this has something to do with it?

Any help would be appreciated. 

Cheers!

**Comment by hsgweon** [comment]
Can you copy and paste a few sequences from your pipits_prep/prepped.fasta here?

**Comment by AMFBio** [comment]
Here you go:

>SAMPLE100_1
ATTCTCCTCCGCTTATTGATATGCTTAAGTTCAGCGGGTATTCTTACCTGATTTGAGGTCAAAAGTTGAGTATCGTATACGAATGATCCTGACGACGCCAAGTCAAACGTACTACATGAGATGGTACGTCATCGCGCGTTCTTAATCAAAGTTGATCTTAAATACGCTTTAATCGTACCGGATGGATGAATTTTAAGCCACTTTGACATGAATCAACATTTGAAAGACGGCTCAATTCCGACGCGATCACCCTTAAAAAAAAGAGCGACGCTTCGATTTTTGTTCTAACGACCCTCAAACAGGCATACTCCCCGGAATACCAGGGAGTGCAATTTGCGTTCAAAGATTCGATGATTCACAAAATTATGCAATTCACACTACTTATCGCATTTCGCTACGTTCTTCATCGATCGC
>SAMPLE100_2
AACATCCTCCGCTTATTGATATGCTTAAGTTCAGCGGGTATTCTTACCTGATTTGAGGTCAAAAGTTGAGTATCGTATACGAATGATCCTGACGACGCCAAGTCAAACGTACTACATGAGATGGTACGTCGTCGCGTGTTCTTAATCAAAGTTGATCTTAAATACGCTTTAATCGTACCGGATGGATGAATTTTAAGCCACTTTGACATGAATCAACATTTGAAAGACGGCTCAATTCCGACGCGATCACCCTTAAAAAAAAGAGCGACGCTTCGATTTTTGTTCTAACGACCCTCAAACAGGCATACTCCCCGGAATACCAGGGAGTGCAATTTGCGTTCAAAGATTCGATGATTCACAAAATTATGCAATTCACACTACTTATCGCATTTCGCTACGTTCTTCATCGACTTA
>SAMPLE100_3
AAAGTCCTCCGCTTATTGATATGCTTAAGTTCAGCGGGTATTCTTACCTGATTTGAGGTCAAAAGTTGAGTATCGTATACGAATGATCCTGACGACGTCAAGTCAAACGTACTACATGAGATGGTACGTCATCGCGCGTTCTTAATCAAAGTTGATCTTAAATACGCTTTAATCGTACCGGATGGATGAATTTCAAGCCACTTTGACATGAATTAACATTTGAAAGACGGCTCAATTCCGACGCGATCACCTTCAAAAAAAAGAGCGACGCTTCGATTTTTTGTTCTAACGACCCTCAAACAGGCATACTCCCCGGAATACCAGGGGGTGCAATTTGCGTTCAAAGATTCGATGATTCACAAAATTATGCAATTCACACTACTTATCGCATTTCACTACGTTCTTCATCGAGATT
>SAMPLE100_5
GACGTCCTCCGCTTATTGATATGCTTAAGTTCAGCGGGTATTCTTACCTGATTTGAGGTCAAAAGTTGAGTATCGTATACGAATGATCCTGACGACGCCAAGTCAAACGTACTACATGAGATGGTACGTCATCGCGCGTTCTTAATCAAAGTTGATCTTAAATACGCTTTAATCGTACCGGATGGATGAATTTTAAGCCACTTTGACATGAATCAACATTTGAAAGACGGCTCAATTCCGACGCGATCACCCTCAAAAAAAAAGAGCGACGCTTCGATTTTTTGTTCTAACGACCCTCAAACAGGCATACTCCCCGGAATACCAGGGAGTGCAATTTGCGTTCAAAGATTCGATGATTCACAAAATTATGCAATTCACACTACTTATCGCATTTCGCTACGTTCTTCATCGATGCT
>SAMPLE100_7
TGGATCCTCCGCTTATTGATATGCTTAAGTTCAGCGGGTATTCTTACCTGATTTGAGGTCAAAAGTTTGAGTATCGTATACGAATGATCCTGATGACGTCAAGTCAAACGTACTACATGAGATGGTACGTTCATCGCGCGTTCTTAACCAAAATTGATCTTAAATACGCTTTAACCGTACCGGATGGATGAATTTCAAGCCACTTTGACATGAATTAACATTTGAAAGACGGCTCAATTCCGACGCGATCACCTTCAAAAAAAAGAGCGACGCTTCGATTTTTTGTTCTAACGACCCTCAAACAGGCATGCTCCCCGGAATACCAGGGAGTGCAATTTGCGTTCAAAGATTCGATGATTCACAAAATTATGCAATTCACACTACTTATCGCATTTCGCTACGTTCTTCATCGACGGT
>SAMPLE100_8
AATGTCCTCCGCTTATTGATATGCTTAAGTTCAGCGGGTATTCTTACCTGATTTGAGGTCAAAAGTTGAGTATCGTATACGAATGATCCTGACGACGCCAAGTCAAACGTACTACATGAGATGGTACGTCATCGCGCGTTCTTAATCAAAGTTGATCTTAAATACGCTTTAATCGTACCGGATGGATGAATTTTAAGCCACTTTGACATGAATCAACATTTGAAAGACGGCTCAATTCCGACGCGATCACCCTTAAAAAAAAGAGCGACGCTTCGATTTTTGTTCTAACGACCCTCAAACAGGCATACTCCCCGGAATACCAGGGAGTGCAACTTGCGTTCAAAGATTCGATGATTCACAAAATTATGCAATTCACACTACTTATCGCATTTCACTACGTTCTTCATCGATCTA
>SAMPLE100_9
GGGTTCCTCCGCTTATTGATATGCTTAAGTTCAGCGGGTATTCTTACCTGATTTGAGGTCAAAAGTTGAGTATCGTATACGAATGATCCTGACGACGCCAAGTCAAACGTACTACATGAGATGGTACGTCATCGCGCGTTCTTAATCAAAGTTGATCTTAAATACGCTTTAATCGTACCGGATGGATGAATTTTAAGCCACTTTGACATGAATCAACATTTGAAAGACGGCTCAATTCCGACGCGATCACCCTTAAAAAAAAGAGCGACGCTTCGATTTTTGTTCTAACGACCCTCAAACAGGCATACTCCCCGGAATACCAGGGAGTGCAATTTGCGTTCAAAGATTCGATGATTCACAAAATTATGCAATTCACACTACTTATCGCATTTCGCTACGTTCTTCATCGAGTGA
>SAMPLE100_10
ATCATCCTCCGCTTATCGATATGCTTAAGTTCAGCGGGTATTCTTACCTGATTTGAGGTCAAAAGTTTGAGTATCGTATACGAATGATCCTGATGACGTCAAGTCAAACGTACTACATGAGATGGTACGTTCATCGCGCGTTCTTAACCAAAATTGATCTTAAATACGCTTTAACCGTACCGGATGGATGAATTTCAAGCCACTTTGACATGAATTAACATTTGAAAGACGGCTCAATTCCGACGCGATCACCCTTAAAAGAAAGAGCGACGCTTCGGTTTTTTGTTCTAACGACCCTCAAACAGGCATACTCCCCGGAATACCAGGGAGTGCAATTTGCGTTCAAAGATTCGATGATTCACAAAATTATGCAATTCACACTACTTATCGCATTTCACTACGTTCTTCATCGATCTG
>SAMPLE100_11
TGTATCCTCCGCTTATTGATATGCTTAAGTTCAGCGGGTATTCTTACCTGATTTGAGGTCAAAAGTTTGAGTATCGTATACGAATGATCCTGATGACGTCAAGTCAAACGTACTACATGAGATGGTACGTTCATCGCGCGTTCTTAACCAAAATTGATCTTAAATACGCTTTAACCGTACCGGATGGATGAATTTCAAGCCACTTTGACATGAATTAACATTTGAAAGACGGCTCAATTCCGACGCGATCACCCTTAAAAAAAAGAGCGACGCTTCGATTTTTTGTTCTAACGACCCTCAAACAGGCATACTCCCCGGAATACCAGGGAGTGCAATTTGCGTTCAAAGATTCGATGATTCACAAAATTATGCACTTCACACTACTTATCGCATTTCACTACGTTCTTCATCGCTGCC
>SAMPLE100_12
GGGCTCCTCCGCTTATTGATATGCTTAAGTTCAGCGGGTATTCTTACCTGATTTGAGGTCAAAAGTTGAGTATCGTATACGAATGATCCTGACGACGTCAAGTCAAACGTACTACATGAGATGGTACGTCATCGCGCGTTCTTAATCAAAGTTGATCTTAAATACGCTTTAATCGTACCGGATGGATGAATTTCAAGCCACTTTGACATGAATTAACATTTGAAAGACGGCTCAATTCCGACGCGATCACCTTCAAAAAAAAGAGCGACGCTTCGATTTTTTGTTCTAACGACCCTCAAACAGGCATACTCCCCGGAATACCAGGGAGTGCAATTTGCGTTCAAAGATTCGATGATTCACAAAATTATGCAATTCACACTACTTATCGCATTTTACTGCGCTCTTCATCGATTAG
>SAMPLE100_13
TTTTTCCTCCGCTTATTGATATGCTTAAGTTCAGCGGGTATTCTTACCTGATTTGAGGTCAAAATTTGAGTATCGTATACGAATGATCCTGACGACGCCAAGTCAAACGTACTACATGAGATGGTACGTCATCGCGCGTTCTTAATCAAAGTTGATCTTAAATACGCTTTAATCGTACCGGATGGATGAATTTTAAGCCACTTTGACATGAATCAACATTTGAAAGACGGCTCAATTCCGACGCGATCACCCTTAAAAAAAAGAGCGACGCTTCGATTTTTGTTCTAACGACCCTCAAACAGGCATACTCCCCGGAATACCAGGGAGTGAAATTTGCGTTCAAAGATTCGATGATTCACAAAATTATGGAATTCACACTACTTATCGCAGTTTGCTGCGTTCTTCATCGAACAG
>SAMPLE100_14
CGGCTCCTCCGCTTATTGATATGCTTAAGTTCAGCGGGTATTCTTACCTGATTTGAGGTCAAAAGTTTGAGTATCGTATACGAATGATCCTGATGACGTCAAGTCAAACGTACTACATGAGATGGTACGTTCATCGCGCGTTCTTAACCAAAATTGATCTTAAATACGCTTTAACCGTACCGGATGGATGAATTTCAAGCCACTTTGACATGAATTAACATTTGAAAGACGGCTCAATTCCGACGCGATCACCCTTAAAAAAAAGAGCGACGCTTCGATTTTTTGTTTTAACGACCCTCAAACAGGCATACTCCCCGGAATACCAGGGAGTGCAATTTGCGTTCAAAGATTCGATGATTCACAAAATTATGCAATTCACACTACTTATCGCATTTCGCTACGTTCTTCATCGAGTAT

**Comment by hsgweon** [comment]
I've just run those sequences myself and they are all valid ITS2 sequences, and all runs as expected.

I have noticed that you are running it in qiime2 environment. Can you run it in PIPITS environment as instructed? That may make a difference as the environment will have its own dependencies. 

Also, are you running it in Mac OS or Ubuntu?

**Comment by hsgweon** [comment]
@AMFBio Are you still experiencing a problem with vsearch? If so, can you send me the output.log file generated in the folder from pipits_process? My email: h.s.gweon@reading.ac.uk

**Comment by AMFBio** [comment]
Hi @hsgweon, just touching base to let you know this is all resolved as per my email. Not an issue with your pipeline - simply an issue with my coding skills :) Thanks for following up.
