### ISSUE TITLE
"You Have 0 Sequences" Error When Running pipits_funits

### ISSUE THREAD

**Issue by brycealex** [hsgweon/pipits#21]
I've been receiving the following error while running pipits_funits on the test data set:

2018-09-18 09:13:01 pipits_funits started
2018-09-18 09:13:01 Checking input FASTA for illegal characters
2018-09-18 09:13:01 ... done
2018-09-18 09:13:01 Counting input sequences
2018-09-18 09:13:01 ... number of input sequences: 7394
2018-09-18 09:13:01 Dereplicating sequences for efficiency
2018-09-18 09:13:01 ... done
2018-09-18 09:13:01 Counting dereplicated sequences
2018-09-18 09:13:01 ... number of dereplicated sequences: 3488
2018-09-18 09:13:01 Extracting ITS2 from sequences [ITSx]
2018-09-18 09:40:19 ... done
2018-09-18 09:40:19 Counting ITS sequences (dereplicated)
2018-09-18 09:40:19 ERROR: You have 0 sequences!

Could you help me with this?

**Comment by hsgweon** [comment]
@boojawaj123 
Can you attach the log file?

**Comment by brycealex** [comment]
^[[91m2018-09-18 09:13:01^[[0m pipits_funits started
^[[91m2018-09-18 09:13:01^[[0m ^[[0mChecking input FASTA for illegal characters^[[0m
^[[91m2018-09-18 09:13:01^[[0m ^[[94m... done^[[0m
^[[91m2018-09-18 09:13:01^[[0m ^[[0mCounting input sequences^[[0m
^[[91m2018-09-18 09:13:01^[[0m ^[[94m... number of input sequences: 7394^[[0m
^[[91m2018-09-18 09:13:01^[[0m ^[[0mDereplicating sequences for efficiency^[[0m
vsearch v2.8.3_linux_x86_64, 1007.8GB RAM, 72 cores
https://github.com/torognes/vsearch

Dereplicating file out_seqprep/prepped.fasta 100%
1961564 nt in 7394 seqs, min 111, max 430, avg 265
Sorting 100%
3488 unique sequences, avg cluster 2.1, median 1, max 179
Writing output file 100%
Writing uc file, first part 100%
Writing uc file, second part 100%
^[[91m2018-09-18 09:13:01^[[0m ^[[94m... done^[[0m
^[[91m2018-09-18 09:13:01^[[0m ^[[0mCounting dereplicated sequences^[[0m
^[[91m2018-09-18 09:13:01^[[0m ^[[94m... number of dereplicated sequences: 3488^[[0m
^[[91m2018-09-18 09:13:01^[[0m ^[[0mExtracting ITS2 from sequences [ITSx]^[[0m
ITSx -- Identifies ITS sequences and extracts the ITS region
by Johan Bengtsson-Palme et al., University of Gothenburg
Version: 1.1b1
-----------------------------------------------------------------
Tue Sep 18 09:13:01 2018 : Preparing HMM database (should be quick)...
Tue Sep 18 09:13:01 2018 : Checking and handling input sequence data (should not take long)...
Tue Sep 18 09:13:02 2018 : Comparing sequences to HMM database (this may take a long while)...
    Tue Sep 18 09:27:12 2018 : Fungi analysis of main strand finished.
    Tue Sep 18 09:40:19 2018 : Fungi analysis of complementary strand finished.
Tue Sep 18 09:40:19 2018 : Analysing results of HMM-scan (this might take quite some time)...
Tue Sep 18 09:40:19 2018 : Extraction finished!
-----------------------------------------------------------------
Thank you for using ITSx!
Please report bugs or unsupported lineages to itsx@microbiology.se

^[[91m2018-09-18 09:40:19^[[0m ^[[94m... done^[[0m
^[[91m2018-09-18 09:40:19^[[0m ^[[0mCounting ITS sequences (dereplicated)^[[0m
^[[91m2018-09-18 09:40:19^[[0m ^[[91mERROR: You have 0 sequences!^[[0m

**Comment by hsgweon** [comment]
And your input command?

**Comment by brycealex** [comment]
pipits_funits -i out_seqprep/prepped.fasta -o out_funits -x ITS2

**Comment by hsgweon** [comment]
Hmm... this is new. Surprised to see that it took 27 minutes to run the test data. What spec is your machine? and which OS are you running it on? Ubuntu? macOS? 

Also can you try:
```
conda install vsearch=2.8.0 -y
```

and then run 
```
pipits_funits -i out_seqprep/prepped.fasta -o out_funits -x ITS2
```

**Comment by brycealex** [comment]
I received the same error unfortunately. I'm running on Ubuntu, accessing a remote server. 

Here are the specs of the server: 

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                72
On-line CPU(s) list:   0-71
Thread(s) per core:    2
Core(s) per socket:    18
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz
Stepping:              1
CPU MHz:               1216.574
CPU max MHz:           3600.0000
CPU min MHz:           1200.0000
BogoMIPS:              4601.18
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K
NUMA node0 CPU(s):     0-17,36-53
NUMA node1 CPU(s):     18-35,54-71

**Comment by brycealex** [comment]
I believe I was running the previous commands incorrectly, but I figured it out. Thank you for your help.

**Comment by hsgweon** [comment]
Can you let me know what the problem was and how you solved it?
