### ISSUE TITLE
pipits_funits "you have 0 sequences" error

### ISSUE THREAD

**Issue by srosten** [hsgweon/pipits#24]
Hello,

I am trying to run fungal sequences with PIPITS but I'm running into issues with the pipits_funits step. I saw that a previous user also had this issue but they did not share their solution. Here is my script and the resulting error message:

`(pipits_env) qiime2@qiime2core2018-4:/media/sf_Shared_Folder/Arctic_Bioremediation_tFINAL/ITS_30Aug2018_undetermined$ pipits_funits -i out_seqprep/prepped.0.fasta -o outfunits_0 -x ITS2 -t 8`

pipits_funits 2.2, the PIPITS Project
https://github.com/hsgweon/pipits
---------------------------------

2018-12-17 13:56:15 pipits_funits started
2018-12-17 13:56:15 Checking input FASTA for illegal characters
2018-12-17 13:56:20 ... done
2018-12-17 13:56:20 Counting input sequences
2018-12-17 13:56:22 ... number of input sequences: 1312800
2018-12-17 13:56:22 Dereplicating sequences for efficiency
2018-12-17 13:56:35 ... done
2018-12-17 13:56:35 Counting dereplicated sequences
2018-12-17 13:56:35 ... number of dereplicated sequences: 154140
2018-12-17 13:56:35 Extracting ITS2 from sequences [ITSx]
2018-12-17 16:43:56 ... done
2018-12-17 16:43:56 Counting ITS sequences (dereplicated)
2018-12-17 16:43:56 ERROR: You have 0 sequences!

I have also included the summary and output files: 
[output.log](https://github.com/hsgweon/pipits/files/2690987/output.log)
[summary.log](https://github.com/hsgweon/pipits/files/2690988/summary.log)

To try to fix this I have tried installing vsearch 2.8.0, splitting the data into smaller groups, and using different numbers of threads. Do you have any suggestions?

Thank you so much!
Shelby

**Comment by hsgweon** [comment]
Is it ITS2 region that you PCR'ed?

**Comment by srosten** [comment]
Hi,

I didn't do the PCR so I wasn't sure which region to use, so I tried both. Yesterday I was able to get some results by using only forward reads and then extracting the ITS1 subregion. However, of 509,022 input sequences to the pipits_process script, there were only 1425 ITS sequences which seems very low. This is the command I used:
`pipits_funits -i out_seqprep_forward/prepped.fasta -o outfunits_forward/ -x ITS1 -t 8`
[ITSx_summary.txt](https://github.com/hsgweon/pipits/files/2698904/ITSx_summary.txt)
[output.log](https://github.com/hsgweon/pipits/files/2698905/output.log)
[summary.log](https://github.com/hsgweon/pipits/files/2698906/summary.log)

Do you have any idea why there are so few sequences?

Thank you so much!
Shelby

**Comment by hsgweon** [comment]
1. Can you find out which primers were used? 2. Could you send me a few sequences from out_seqprep_forward/prepped.fasta You can either copy and paste them here, or if you don't want to disclose them here, send them to me (my email address is on the main page). BTW, I'm on leave this week, so I won't be able to look at it until January.

**Comment by DrCBG** [comment]
Is anyone monitoring this thread? Posting a solution would be great since this issue (...and others) appear to be part of an ongoing issue with anyone using the PIPITS program.

**Comment by hsgweon** [comment]
Closing this for now as @srosten hasn't responded.
