### ISSUE TITLE
pipits_prep parses file names badly

### ISSUE THREAD

**Issue by Roli-Wilhelm** [hsgweon/pipits#27]
Hi,
I had several 'water blanks' (negative controls) in my dataset. These were given names "water_blank_1", "water_blank_2", "water_blank_3" etc. After the initial 'pipits prep' step, there was only a single 'water' sample remaining. If I had to guess, your script is overwriting the samples after splitting on the delimiter "_". If true, your pipeline is broken. It is not advisable to parse file names based on "_", as this is a very common delimiter used in naming. Please fix this. It will only cause further headache.

Thanks!

**Comment by Roli-Wilhelm** [comment]
Note: the user could provide you a list of sample names at that step to ensure proper parsing.

**Comment by Roli-Wilhelm** [comment]
delimiter "\_"

**Comment by hsgweon** [comment]
> If I had to guess, your script is overwriting the samples after splitting on the delimiter "".

If you have read the instruction, it says "Sample IDs are taken from the first characters preceding an underscore (“_”) from each filename". 

>  If true, your pipeline is broken. It is not advisable to parse file names based on "", as this is a very common delimiter used in naming.

This convention is taken from BaseSpace (Illumina), and it may not convenient to you, but I wouldn't go as far as saying the pipeline is broken. PIPITS is not a generic pipeline but designed to work with data from Illumina, and BaseSpace auto-corrects underscores in sample IDs to hyphens.


> Note: the user could provide you a list of sample names at that step to ensure proper parsing.

Yes, you can do this in PIPITS. Modify the SAMPLE ID list file ("readpairslist.txt")

From:
water_blank_1   water_blank_1_L001_R1_001.fastq.bz2   water_blank_1_L001_R2_001.fastq.bz2
water_blank_2   water_blank_2_L001_R1_001.fastq.bz2   water_blank_2_L001_R2_001.fastq.bz2

To:
water-blank-1   water_blank_1_L001_R1_001.fastq.bz2   water_blank_1_L001_R2_001.fastq.bz2
water-blank-2   water_blank_2_L001_R1_001.fastq.bz2   water_blank_2_L001_R2_001.fastq.bz2

So you don't actually have to change file names, but just modify the readpairslist.txt and you are good to go.

**Comment by Roli-Wilhelm** [comment]
Thanks for clarifying! I apologize for sounding ornery.

I do, however, maintain that parsing by "\_" is not a good standard practice (regardless of whether it is stated in your manual or anticipating filenames directly output from the sequencer).

**Comment by hsgweon** [comment]
I know how you feel - we all like to use underscores in filenames (sort of treating it like a space). But there is a reason for not allowing underscores in sample ids. For instance, how is PIPITS able to guess the sample id from the filenames alone when sequencers typically produce filenames like "water_blank_1_S87_L001_R2_001.fastq.bz2"? The only way is to let users to provide their own list of sample names, and that's a feature PIPITS supports.
