### ISSUE TITLE
Question on runtime of pipits_funits step

### ISSUE THREAD

**Issue by davidkim8** [hsgweon/pipits#28]
Dear Hyun,

First, I apologize if this is not the right place to ask questions. I have used your test dataset and all steps worked fine for me.

When using my dataset, pipits_funits step (hmmsearch) seems to be taking longer than expected. Currently, the progress output has been stopped at "2019-01-07 19:06:58 Extracting ITS1 from sequences [ITSx]" for about 4 days. According to the MacOS Activity Monitor, terminal is still processing the command. As the process seems to be still running, I checked the size of output files. Under "intermediate" folder, the "derep.fasta" is at 945.3 MB, "derep.summary.txt" is at 162 bytes, and "derep.uc" is at 398.7 MB and have not changed in size for a while.

Is this a simple computing speed issue? This computer has 8 GB of memory and pispino_seqprep output says I have 6441992 sequences prepped.

Thank you and please let me know if I should provide additional information.

**Comment by hsgweon** [comment]
@davidkim8 
I think it's still running if it hasn't crashed out.
It can take a lot of time depending on the diversity of your samples (can take more than a week especially from soil samples - and 6 million reads are quite a lot - must be an exciting project!). One way to speed things up is by subdividing your prepped.fasta into, let's say 30 files, and then run pipits_funits separately (depending on the number of CPUs you have), and then combine all the resulting files into one for the next and final step. This would significantly reduce the processing time (provided that you have multiple CPUs). At the moment, you have to do this manually, but indeed this is a feature that I would like to implement in the next PIPITS release. Estimating time to complete the process is another feature that I want to add. It's all doable but with other commitments in my new job, I am not able to find sufficient time other than debugging here and there, but it's on my agenda! 

Can you leave it to run for another day and see if anything in the intermediate folder has changed? sorry this is not ideal!

**Comment by davidkim8** [comment]
Thanks for quick reply!

I will keep it running in the background and see what happens. It was indeed an exciting project and wanted to test out PIPITS as we are gearing towards another project, which should have much less reads. I think this computer has 4 threads so perhaps I will also give splitting prepped.fasta a try.

Thanks again and I will keep you posted.

David

**Comment by davidkim8** [comment]
So I waited about a week and decided to stop the process. Instead, I took your suggestion and split the prepped.fasta file by sample and decided to process one of the sample by itself. This had 34021 reads, which is ~0.5% of the initial full data set I tried to work with. This process took ~4 hours, so if I extrapolate this to my full dataset (6441992 reads), I think it would have taken almost 33 days to process it. Next up, I will see if I can run 4 processes at the same time and see if that would be helpful.

Thanks again for the troubleshooting tips!

David

**Comment by hsgweon** [comment]
Thanks for the update! It's got to be a great project, and sorry for not being able to help much. 

This really can be improved even by doing simple clustering at 99% to reduce the number of reads etc... Or if ITSx guys implement multithreading (properly). But they probably have the same issue as I do - no staff/student/time! In any case, if you get stuck and need me to process your data as collaboration (I have access to some big machines), then do let me know. We can think of something. Meanwhile, best of luck with it.

**Comment by mradz19** [comment]
Hey hsgwein,

Following on from this question. I am running pipits on a sample containing 12,970,625 reads generated form illumina shotgun sequencing. I have set the -t to 44 which has split the fasta file into 44 seperate files. pipits_funits has now been running for approx 3.5h hours and the last file generated so far is the derep.uc file. Is this to be expected given the input regardless of the 44 threads I have set?

**Comment by hsgweon** [comment]
That's right, and it's running as expected. If it hasn't produced any errors, then it's still running. pipits_funits step is a very time consuming step, and depending on the diversity of your sample, it can take as long as days (some of my gigantic study from soil took nearly a week).
