### ISSUE TITLE
Issue with Pipits_ process

### ISSUE THREAD

**Issue by Biomassuark** [hsgweon/pipits#31]
ERRO: environment variables (PIPITS_UNITE_REFERENCE_DATA_CHIMERA, PIPITS_UNITE_RETRAINED_DIR, PIPITS_WARCUP_RETRAINED_DIR) are not set. Please see PIPITS installation for an instruction on this.
(pipits_env) 

I am getting the above issue and also unable to update to PIPITS 2.3

**Comment by hsgweon** [comment]
Sorry it's taking awhile for the bioconda package to catch up. It should be ready soon though.

**Comment by hsgweon** [comment]
I've just read that VSEARCH's dereplication no longer allows "--threads" option - how annoying! I will have to make a change and re-upload PIPITS onto the bioconda repository. I will keep you posted.

**Comment by hsgweon** [comment]
Ok, all passed the test, and processed ITS data without any issues (tested it on a freshly installed Ubuntu 18.04 and macOS Mojave). 

If you find any issues, please do raise it again. For now I will close this thread.
