### ISSUE TITLE
Pipits process: UCHIME database MD5 checksum

### ISSUE THREAD

**Issue by EmiliaHannula** [hsgweon/pipits#32]
Error is as follows:

2019-05-14 09:31:04 Downloading UCHIME database for chimera filtering:
2019-05-14 09:31:04 ... DB directory and files exits, but seems to be different/corrupt -> re-downloading...
[###################################################################################################]100% |   8.6 MiB/s | 4578703 of 4578703 | Time:  0:00:00
File size: 4.37 MB
Downloaded data is corrupt. Get in touch with PIPITS team!. Exiting...

This only appears in the latest version and I think is due to md5 checksum not being correct for the UCHIME database it downloads. I have deleted earlier versions of the database from the bin already and that did not solve the problem. 

Any ideas how to solve this?

Thanks!

**Comment by hsgweon** [comment]
Can you please try:

source activate pipits_env
conda update pipits

When did you install pipits? and which platform are you using (i.e. macOS? Ubuntu?)

**Comment by EmiliaHannula** [comment]
I upgraded to the newest version just last week, and this is the first time I try to run the process step with the new version (all other steps run fine):
Name                    Version                   Build  Channel
pipits                    2.3                      py36_1    bioconda

If i try to force update I get an error that we have py36_1 version and not 36_4. I cannot force the system to update this. 

I am using our server (Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-146-generic x86_64)). 

I have run this step many times earlier and this is the first time I get this error.

**Comment by hsgweon** [comment]
Hmm, the version should be pipits-2.3-py36_4 (bioconda)
Can you either try to update pipits, or delete the pipits environment and install it again?

To delete the environment:
`
conda remove --name pipits_env --all
`

Can you let me know how you get on?

**Comment by EmiliaHannula** [comment]
Deleting the environment and installing it again helped and now it runs ok.

Thanks for the help.
