### ISSUE TITLE
error in phylotyping with pipits 2.4

### ISSUE THREAD

**Issue by FabWei** [hsgweon/pipits#36]
Dear hsgweon,

I recently ran pipits 2.4 with a job of 53 million reads. I used an SGE (SUSE linux). 
pipits_process produced a broken phylotype table: abundances with decimals and as minor issue, the first column was named "OTU ID" and filled with taxonomy.
I reproduced the error by running the pipis_process step (pipits 2.4) on Ubuntu 18.04.1 (WSL version). 
Running just pipits_process in a pipits 2.3 environment solved the problem for me. 
Running the test data under 2.4 also produced the strange looking phylotype table, but with whole numbers (no difference between OTUs and phylotypes in test data, maybe) .
Therefore, I guess there might be some error hidden the phylotyping step of pipits 2.4?

Cheers and many thanks for your regular updates,
Fabian

**Comment by hsgweon** [comment]
Hi @FabWei 

I am on leave from today and will travelling until January - this actually is good news because I can spend time to fix/update/upgrade PIPITS (which I enjoy generally). Not been able to find time during term times due to my work commitment... sadly.

Please do keep me updated when you find bugs/issues. I will do my bestestest to resolve it!

Best
Soon

**Comment by hsgweon** [comment]
Hopefully this is now fixed with the new update. I will close this for now, but if this problem persists, do let me know.

**Comment by FabWei** [comment]
Hi again!
Unfortunately, the problem still exists in pipits_process 2.5 as it did in 2.4. 
In short, instead of phylotype-IDs the according column of the phylotype_table.txt still gets filled with all the taxonomy of the phylotype. 
In addition, I get phylotype abundances with decimals when running my own data on these versions of pipits_process. Because of the decimals I think I cannot trust this table. Do you have an easy recommendation how I can quickly get around this issue? I want to do a follow-up on an older study   needing phylotypes very soon, and would be glad for any help!

**Comment by hsgweon** [comment]
Hi @FabWei  Would you be able to send me a quick email with your results if you don't mind (my email is displayed here: https://github.com/hsgweon), and possibly send some of your sequences (first hundreds)? Phylotype abundances in the resulting file are displayed in decimals but all should end with ".0".
