### ISSUE TITLE
How to analyze ITS from Ion PGM reads?

### ISSUE THREAD

**Issue by Kur1sutaru** [hsgweon/pipits#41]
The primary pipeline is for Illumina paired-end
But my dataset are from Ion PGM
How I do this? Thanks for the atention

**Comment by hsgweon** [comment]
Sorry PIPITS isn't really designed to handle Ion PGM datasets, and I am not looking to implement this in the future either.

**Comment by Kur1sutaru** [comment]
Thanks!
