### ISSUE TITLE
ERROR: You have 0 sequences identified as ITS1. Are you sure your sequences are ITS1?

### ISSUE THREAD

**Issue by gxenomics101** [hsgweon/pipits#42]
Hi,

I'm using the current version of Pipits on Ubuntu 18.04. The program has been working fine with ITS2 datasets but I keep encountering an error (see subject field) from ITSx when processing data generated with the BITS (ACCTGCGGARGGATCA) and B58S3 (GAGATCCRTTGYTRAAAGTT) primers.
 
In addition to my own data, I tried to process a published BITS data set that has successfully used pipits, and encountered the same error: ERROR: You have 0 sequences identified as ITS1. Are you sure your sequences are ITS1? 

The data set used to verify my original issue was PRJEB32659 (A meta-barcoding analysis of soil mycobiota of the upper Andean Colombian agro-environment. Scientific Reports volume 9, Article number: 10085 (2019).

Cheers, Greg

**Comment by hsgweon** [comment]
Hi Greg @gxenomics101 

One of the key issue with ITSx is that it needs at least one the conserved region flanking ITS1 or ITS2. Can you check with just a few sequences to see if they have both priming site at the ends? 
If your sequences don't have any conserved regions, then you can skip pipits_funits altogether and move straight to pipits_process

**Comment by gxenomics101** [comment]
Both data sets have the fwd/rev BITS primers. I'll try adding a little extra conserved flanking sequence to prepped.fasta and see if that works and also try removing the primers and move straight to pipits_process.

Thanks for the help.
