### ISSUE TITLE
Issues accessing classifier.jar within PIPETS PROCESS

### ISSUE THREAD

**Issue by rjmseq** [hsgweon/pipits#46]
Hi @hsgweon, I hope all is well!

I'm planning on using the PIPITS pipeline for some MiSeq data analysis. I'm currently in the process of testing PIPITS installation (as advised in the guide) but I'm having issues accessing the rdp classifier to assign taxonomy for my final OTU table:

![image](https://user-images.githubusercontent.com/79907887/109636869-fe099c00-7b43-11eb-9b98-0dcc840bdc81.png)

 
Classifier.jar is present in the relevant directory, and file permissions seem okay... any ideas?

![image](https://user-images.githubusercontent.com/79907887/109636913-0cf04e80-7b44-11eb-95d3-e102d8fc2e7b.png)

Sorry if I'm missing something drastic! I'm new to Linux (Ubuntu) and this pipeline, with all my previous work focused to 16S rRNA pipelines in R). 

Best wishes
Ryan

**Comment by rjmseq** [comment]
Problem was with unzipping classifier - fixed issue!

**Comment by hsgweon** [comment]
@rjmseq 
Glad the issue has been fixed.

Just to note - if you followed the instruction on the first page of this github, it's been advised to use a conda environment to run PIPITS, but looking at the screenshot above, it looks like this isn't the case. In any case, if you can run it and can produce an OTU table, then that's all that matters! The problem can occur if you install other tools which use different version of the dependencies that PIPITS use, so beware of this.

Good luck with the analysis.

**Comment by rjmseq** [comment]
You are correct, I have run in the absence of a conda environment. OTU tables have been produced, but I will bear this in mind moving forward!

BW
Ryan
