### ISSUE TITLE
is there a way to create a list with sample names with multiple fields?

### ISSUE THREAD

**Issue by lcamVz** [hsgweon/pipits#47]
I am looking to run PIPITS but my samples have multiple fields and I know that pipits takes the first field with delimiter "_". 

111_M_0_Rhizo_ITS_R1_001.fastq.gz
111_M_0_Rhizo_ITS_R2_001.fastq.gz

Any recommendations.

**Comment by hsgweon** [comment]
@lcamVz

I would manually create the readpairslist.txt (tab-delimited file) as the following:

111-M-0-Rhizo-ITS   111_M_0_Rhizo_ITS_R1_001.fastq.gz     111_M_0_Rhizo_ITS_R2_001.fastq.gz
112-M-0-Rhizo-ITS   112_M_0_Rhizo_ITS_R1_001.fastq.gz     112_M_0_Rhizo_ITS_R2_001.fastq.gz
...

And then test it and see if you get the desired results? I am sure this will be fine, but in case not, then you will have to rename the files to:
111-M-0-Rhizo-ITS_R1_001.fastq.gz
111-M-0-Rhizo-ITS_R2_001.fastq.gz

Hope this helps, but if not do let me know.

BTW, these days, BASESPACE (the software Illumina sequencers run internally) outputs files without underscores in the sample names in the same manner PIPITS work, so the filenames straight from sequencing should look more like "111-M-0-Rhizo-ITS_R1_001.fastq.gz" in general anyway, but I guess that depends when you sequenced it and by whom.

**Comment by lcamVz** [comment]
Yes, I was thinking about that why it was with _ when usually is -, thank you for the suggestions. I'll try them and see what works.

**Comment by lcamVz** [comment]
We got a successful run with PIPITS! Thanks!!

**Comment by hsgweon** [comment]
@lcamVz 
Excellent!

Closing.
