### ISSUE TITLE
ImportError: No module named pipits - Error: None zero returncode

### ISSUE THREAD

**Issue by alabba** [hsgweon/pipits#48]
Dear all,

    I tested PIPITS (latest version) on the 'data_test' and everything has gone well (running on the frontend).
I submitted a job via `qsub` using my data sequencing, but the job has been killed after '
`pipits_funits` step.

In details, .sh script is the following:

```
#!/bin/bash
conda init bash
source ~/.bashrc
conda activate pipits_env
pipits_funits -i prepped.fasta -o out_funits_ITS2 -x ITS2 -r -t 30   

```
I submitted  it via qsub and the following is the content of 'output.log':

(base) [alabbate@ui03 out_funits_ITS2]$ cat output.log 
pipits_funits 2.7, the PIPITS Project
https://github.com/hsgweon/pipits
---------------------------------

2021-04-19 15:53:33 pipits_funits started
2021-04-19 15:53:33 Checking input FASTA for illegal characters
2021-04-19 15:53:45 ... done
2021-04-19 15:53:45 Counting input sequences
2021-04-19 15:53:54 ... number of input sequences: 4190427
2021-04-19 15:53:54 Dereplicating sequences for efficiency
vsearch v2.17.0_linux_x86_64, 251.7GB RAM, 40 cores
https://github.com/torognes/vsearch

Dereplicating file /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_seqprep_plate3/prepped.fasta 100%
1462933517 nt in 4190427 seqs, min 100, max 582, avg 349
Sorting 100%
2118105 unique sequences, avg cluster 2.0, median 1, max 38177
Writing output file 100%
Writing uc file, first part 100%
Writing uc file, second part 100%
2021-04-19 15:54:30 ... done
2021-04-19 15:54:30 Counting dereplicated sequences
2021-04-19 15:54:35 ... number of dereplicated sequences: 2118105
2021-04-19 15:54:35 Splitting sequences to multiple parts
[INFO] split into 30 parts
[INFO] read sequences ...
[INFO] read 2118105 sequences
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_001.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_002.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_003.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_004.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_005.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_006.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_007.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_008.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_009.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_010.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_011.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_012.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_013.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_014.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_015.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_016.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_017.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_018.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_019.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_020.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_021.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_022.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_023.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_024.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_025.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_026.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_027.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_028.fasta
[INFO] write 70604 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_029.fasta
[INFO] write 70589 sequences to file: /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/split/derep.part_030.fasta
2021-04-19 15:54:57 ... done
2021-04-20 01:48:07 Counting ITS sequences (dereplicated)
2021-04-20 01:48:07 ... number of ITS sequences (dereplicated): 124443
2021-04-20 01:48:07 Sorting by ID
[INFO] read sequences ...
[INFO] 124443 sequences loaded
[INFO] sorting ...
[INFO] output ...
2021-04-20 01:48:10 ... done
2021-04-20 01:48:10 Removing short sequences below < 100bp
vsearch v2.17.0_linux_x86_64, 251.7GB RAM, 40 cores
https://github.com/torognes/vsearch

Reading input file 100%
124309 sequences kept (of which 0 truncated), 134 sequences discarded.
2021-04-20 01:48:10 ... done
2021-04-20 01:48:10 Counting length-filtered sequences (dereplicated)
2021-04-20 01:48:10 ... number of length-filtered sequences (dereplicated): 124309
2021-04-20 01:48:10 Re-inflating sequences
Traceback (most recent call last):
  File "/lustrehome/alabbate/.conda/envs/pipits_env/bin/pipits_rereplicate", line 31, in <module>
    from pipits import pipits_SeqIO as SeqIO
ImportError: No module named pipits
2021-04-20 01:48:11 Error: None zero returncode: python /lustrehome/alabbate/.conda/envs/pipits_env/bin/pipits_rereplicate -i /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/derep.ITS2.sizefiltered.fasta -o /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/ITS.fasta --uc /lustre/home/alabbate/2018_hany_in_bari/analyses/pipits/plate3/out_funits_ITS2/intermediate/derep.uc

Do you have any suggestions to fix it?
Thank you in advance for your precious help.

Best,

AL

**Comment by FabWei** [comment]
Hello!
The error message you got is 

> "ImportError: No module named pipits"

Im am not an expert for job schedulers and all setups differ from each other, but this looks like your backend has no idea where to find pipits. 
My general personal solution for such errors (I have no admin rights on our computing grid) is to install everything in my personal folder and run it from the current working directory. 
In my qsub-script, I simply added this to the header:
```
# run in current working directory
#$-cwd
```
No warranity, but with "copy working directory" pipits and many other tools ran successfully.

**Comment by alabba** [comment]
I tried to import the module from the frontend, inside pipits_env and no error popped out. 
So, it looks like if the pipits_env has been deactivated at some point.

I'm going to edit the script as you suggested, but I have a doubt. 
Do you mean this?

```
#!/bin/bash
**#$-cwd**
conda init bash
source ~/.bashrc
conda activate pipits_env
pipits_funits -i prepped.fasta -o out_funits_ITS2 -x ITS2 -r -t 30
```

**Comment by FabWei** [comment]
`#$` Is the way my grid scheduler recognises parameters for how the job is to be executed. May be different in your case, e.g. `#PBS` . `-cwd` is a parameter my grid scheduler understands. Yours may be different - you could check the help for your version of qsub / job-scheduler, maybe you find a parameter there that solves your problem.



A working script (that I hand out to students) on our system can look like this:
```
# script to be forwarded to computing backend using the "qsub" command from a terminal in the frontend of the server
# which shell to use
#$-S /bin/bash
# run in current working directory
#$-cwd
# name of error log file
#$-e error.log
# name of output log file
#$-o main.log
# specify parallel environment (e.g. "hmp20" allows max. 20 threads/processors with each their own amount of memory)
#$ -pe hmp 20
# name of the job
#$-N TEST_JOB

# read https://github.com/hsgweon/pipits before using this

# activate the pipeline environment, named during pipits installation 
conda activate pipits_env

# make a list of samples with forward and reverse reads, check the list entries yourself
pispino_createreadpairslist -i rawdata -o readpairslist.txt

# merging of forward and reverse reads with basic quality checks 
pispino_seqprep -i rawdata -o out_seqprep -l readpairslist.txt -t 19 -v 

# extract sequences with real ITS fragment content
pipits_funits -i out_seqprep/prepped.fasta -o out_funits -v -t 19 -x ITS2

# cluster otus, assess taxonomy
pipits_process -i out_funits/ITS.fasta -o out_process -v -t 19 --warcup

# reformat tables for later (not strictly necessary)
pipits_funguild.py -i out_process/otu_table.txt -o out_process/otu_table_funguild.txt
pipits_funguild.py -i out_process/phylotype_table.txt -o out_process/phylotype_table_funguild.txt

# deactivate the pipeline environment
conda deactivate
```

**Comment by alabba** [comment]
Ok, thanks for the clarification. I will check for the right syntax.
I will keep you updated.
