### ISSUE TITLE
FUNITS -t command is it specific for cpus or threads?

### ISSUE THREAD

**Issue by lcamVz** [hsgweon/pipits#52]
I am running FUNITS step and the I indicate -t 30 I got an error that says that I have only 2 cpu. my question is the -t is it to specify cpus or number of threads? I have dual cpu 20 cores and 40 threads workstation.  It gave me the same error in both 20 and above integers but it ran when only used 2 as an integer.

**Comment by hsgweon** [comment]
PIPITS uses a command "multiprocessing.cpu_count()", and it will count how many logical processors your system has, so not sure why it says 2... 

Can you run python from your terminal and then type following?

```
import multiprocessing
multiprocessing.cpu_count()
```

If it says 2, then I have no idea what's going on!

**Comment by lcamVz** [comment]
I try importing multiprocessing and I get import-im6.q16: unable to open X server '@ error/import.c/ImportImageCommand/359.
