### ISSUE TITLE
PIPITS_process error linked to the UNITE_retrained_28.06.2017 reference

### ISSUE THREAD

**Issue by arbernard** [hsgweon/pipits#6]
Hi Mr Gweon,

I'm currently trying to use PIPITS 1.5 on a cluster where PIPITS have been installed by a system administrator for all users.

Unfortunatly, I'm facing an error with the last tool of the workflow: PIPITS_process.

The error is as follow:

> Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: /path/to/pipits/install/PIPITS-1.5.0/refdb/UNITE_retrained_28.06.2017/rRNAClassifier.properties (Permission denied)

After encountering this error I downloaded the UNITE_retrained_28.06.2017 archive myself (from the sourceforge repository) and I checked the default permissions of the files.

All the other files have `-rw-r--r--` as permissions but the rRNAClassifier.properties has only `-rw-------`.

Maybe you should reupload a new version of the archive with fixed default permission for this rRNAClassifier.properties file so that other people don't fall in the same trap as I did ? :)

Thanks in advance

A.B

**Comment by arbernard** [comment]
I also noticed today that the `rRNAClassifier.properties` file of the Warcup archive is also affected by this default permission issue.

**Comment by hsgweon** [comment]
The new PIPITS 2.0 hopefully should have resolved this issue, but do let me know if this is not the case.
