### ISSUE TITLE
pipits_prep command issue

### ISSUE THREAD

**Issue by mirzaabidpp** [hsgweon/pipits#7]
Hi, 
I am trying to work out on your pipeline I installed all dependencies including ITSx. But after installation as you mentioned in synopsis, i tried to run test data and used command pipits_prep -i rawdata -o pipits_prep -l readpairslist.txt but i found below mentioned output and unable to move forward to command pipits_funits -i pipits_prep/prepped.fasta -o pipits_funits -x ITS2

2017-10-31 03:26:13 PIPITS_PREP started
2017-10-31 03:26:13 Processing the listfile
2017-10-31 03:26:13 Counting sequences in rawdata
2017-10-31 03:26:13   Number of reads: 75
2017-10-31 03:26:13 Reindexing forward reads
2017-10-31 03:26:13 Reindexing reverse reads
2017-10-31 03:26:13 Joining paired-end reads [VSEARCH]
2017-10-31 03:26:13 ERROR: None zero returncode: vsearch --fastq_mergepairs pipits_prep/tmp/reindex_fastq_F/A01B.fastq --reverse pipits_prep/tmp/reindex_fastq_R/A01B.fastq --fastqout pipits_prep/tmp/joined/A01B.fastq --threads 1 --fastq_allowmergestagger --fastq_maxdiffs 500 --fastq_minovlen 20 --fastq_minmergelen 100

I am anxiously waiting for your quick and favorable response.
Abid

**Comment by pedres** [comment]
I have the same problem, working with a Biolinux 8 distribution. As mirzaabidpp I ahve installed pipits and all the dependencies (no problems with section 1.6 of tutorial) but when run pipits_prep -i rawdata -o pipits_prep -l readpairslist.txt  I get
ERROR: None zero returncode: vsearch --fastq_mergepairs pipits_prep/tmp/reindex_fastq_F/A01B.fastq --reverse pipits_prep/tmp/reindex_fastq_R/A01B.fastq --fastqout pipits_prep/tmp/joined/A01B.fastq --threads 1 --fastq_allowmergestagger --fastq_maxdiffs 500 --fastq_minovlen 20 --fastq_minmergelen 100

I have tried to remove the files for sample AO1B and edit the readpairslist.txt but I get the same error message but wtih AO2B. I cannot understand this problem.

Regards

Manuel

**Comment by hsgweon** [comment]
I do apologise. I have moved to a new job so I have not been able to maintain the pipeline. I will have a look as soon as possible and let you know.

**Comment by orchid677** [comment]
I have the same error but it has been months with no answer to the problem so I fear this is yet another tool created and then abandoned. How frustrating. Please let us know if you ever will respond or if we should stop using pipits. 

Did anyone else solve the problem?

**Comment by R-Huerlimann** [comment]
My none zero returncode problem was with a different command (see: [https://github.com/hsgweon/pipits/issues/8](url)); however, I solved it by running the different steps myself, following the steps written in the python code. My grasp of python isn't good enough to quickly fix the issue within a reasonable time frame, but if I have to use it again, I will probably just list the different commands in a shell script.

**Comment by orchid677** [comment]
Hi R-Huerliman. Thanks for the idea. I have been debugging the run and I think, in my case, there is a problem assembling two paired read files. I'm not sure exactly why (other programmes can merge the two files) but when I remove the problematic files the run goes further (not done yet). So I'm not sure why the error, but removing some input files seems to be allowing it to proceed.

**Comment by R-Huerlimann** [comment]
Have you tried to run the command outside of pipits and see if it finishes with all the files included? Would be interesting to see if it is an issue with pipits or the merging software.

**Comment by hsgweon** [comment]
Sorry it's been long. Can you try to install and run it with PIPITS 2.0, and also try with --forwardreadsonly option to see what you get if you don't join? 

The command is no longer pipits_prep but it's called pispino_seqprep

**Comment by kediza** [comment]
Hi I am also having an error 

 pipits_funits -i /mnt/lustre/users/out_seqprep/prepped.fasta -o out_funits3 -x ITS2
pipits_funits 2.2, the PIPITS Project
https://github.com/hsgweon/pipits
---------------------------------

2018-09-27 16:34:55 pipits_funits started
2018-09-27 16:34:55 Checking input FASTA for illegal characters
2018-09-27 16:35:13 ... done
2018-09-27 16:35:13 Counting input sequences
2018-09-27 16:35:17 ... number of input sequences: 7029909
2018-09-27 16:35:17 Dereplicating sequences for efficiency
2018-09-27 16:35:18 Error: None zero returncode: vsearch --derep_fulllength /mnt/lustre/users/out_seqprep/prepped.fasta --output out_funits3/intermediate/derep.fasta --uc out_funits3/intermediate/derep.uc --fasta_width 0 --sizeout ,

Kindly assist

**Comment by hsgweon** [comment]
@kediza Can you please try:

```
conda install vsearch=2.8.0
```

and then re-run the command?

**Comment by kediza** [comment]
Hi

Thanks for your reply, I did as advised and this is the error I got
PermissionError:
[Errno 13] Permission denied:
'/apps/chpc/bio/anaconda3/envs/pipits_env/.condatmp'

Regards

**Comment by hsgweon** [comment]
@kediza I'm not entirely sure what the problem is there. Did you have the same problem when you ran the test data?

**Comment by JiaruiChen** [comment]
> @kediza I'm not entirely sure what the problem is there. Did you have the same problem when you ran the test data?

Hi

I am using the test data these days following the manual but having the same problem of ''None zero returncode" in the Seuqence Preparation part. And all the former commands were fine with correct environment. Do you have any idea of this issue?

Best regards,

**Comment by JiaruiChen** [comment]
Dear all,

I was having the same issue but somehow I figure it out. 

I think it may relate to the conflict of different version of vsearch. Since our server had installed vsearch before and the pipits environment also contain another vsearch. Therefore it would report 'Illegal instruction' when you call the vsearch. 

What I did is replace the vsearch in pipits environment (which is stored in /anaconda/bin/envs/pipits_env/bin/vsearch) with our own vsearch and it works. 

Best regards,

**Comment by hsgweon** [comment]
@JiaruiChen Many thanks for this. May I ask whether you are running it on a Ubuntu server?

**Comment by JiaruiChen** [comment]
> @JiaruiChen Many thanks for this. May I ask whether you are running it on a Ubuntu server?

We are using Debian
